NerdDinner/NerdDinner/Models/Dinner.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data.Linq;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;

namespace NerdDinner.Models
{
    public partial class Dinner
    {

        public bool IsValid
        {
            get { return (GetRuleViolations().Count() == 0); }
        }

        public IEnumerable<RuleViolation> GetRuleViolations()
        {
            if (String.IsNullOrEmpty(Title))
                yield return new RuleViolation("Title required", "Title");

            if (String.IsNullOrEmpty(Description))
                yield return new RuleViolation("Description required", "Description");

            if (String.IsNullOrEmpty(HostedBy))
                yield return new RuleViolation("HostedBy required", "HostedBy");

            if (String.IsNullOrEmpty(Address))
                yield return new RuleViolation("Address required", "Address");

            if (String.IsNullOrEmpty(Country))
                yield return new RuleViolation("Country required", "Country");

            if (String.IsNullOrEmpty(ContactPhone))
                yield return new RuleViolation("Phone# required", "ContactPhone");

            if (!PhoneValidator.IsValidNumber(ContactPhone, Country))
                yield return new RuleViolation("Phone# does not match country", "ContactPhone");

            yield break;
        }

        partial void OnValidate(ChangeAction action)
        {
            //if (!IsValid)
            //    throw new ApplicationException("Rule violations prevent saving");
        }

        public bool IsHostedBy(string userName)
        {
            return HostedBy.Equals(userName, StringComparison.InvariantCultureIgnoreCase);
        }

        public bool IsUserRegistered(string userName)
        {
            return RSVPs.Any(r => r.AttendeeName.Equals(userName, StringComparison.InvariantCultureIgnoreCase));
        }
    }

    public class PhoneValidator
    {

        static IDictionary<string, Regex> countryRegex = new Dictionary<string, Regex>() {
           { "USA", new Regex("^[2-9]\\d{2}-\\d{3}-\\d{4}$")},
           { "UK", new Regex("(^1300\\d{6}$)|(^1800|1900|1902\\d{6}$)|(^0[2|3|7|8]{1}[0-9]{8}$)|(^13\\d{4}$)|(^04\\d{2,3}\\d{6}$)")},
           { "Netherlands", new Regex("(^\\+[0-9]{2}|^\\+[0-9]{2}\\(0\\)|^\\(\\+[0-9]{2}\\)\\(0\\)|^00[0-9]{2}|^0)([0-9]{9}$|[0-9\\-\\s]{10}$)")},
    };

        public static bool IsValidNumber(string phoneNumber, string country)
        {

            if (country != null && countryRegex.ContainsKey(country))
                return countryRegex[country].IsMatch(phoneNumber);
            else
                return false;
        }

        public static IEnumerable<string> Countries
        {
            get
            {
                return countryRegex.Keys;
            }
        }

    }

    public class RuleViolation
    {

        public string ErrorMessage { get; private set; }
        public string PropertyName { get; private set; }

        public RuleViolation(string errorMessage, string propertyName)
        {
            ErrorMessage = errorMessage;
            PropertyName = propertyName;
        }
    }

}

NerdDinner/NerdDinner/Controllers/DinnersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NerdDinner.Models;

namespace NerdDinner.Controllers
{
    public class DinnersController : Controller
    {

        DinnerRepository dinnerRepository = new DinnerRepository();

        //
        // GET: /Dinners/
        //    /Dinners/[paging]

        public ActionResult Index(int? page)
        {

            //var dinners = dinnerRepository.FindUpcomingDinners().ToList();

            const int pageSize = 5;

            var upcomingDinners = dinnerRepository.FindUpcomingDinners();
            var paginatedDinners = new PaginatedList<Dinner>(upcomingDinners, page ?? 0, pageSize);

            return View(paginatedDinners);
        }

        //
        // GET: /Dinners/Details/[ID]

        public ActionResult Details(int id)
        {

            Dinner dinner = dinnerRepository.GetDinner(id);

            if (dinner == null)
                return View("NotFound");
            else
                return View(dinner);
        }

        //
        // GET: /Dinners/Edit/[ID]
        [Authorize]
        public ActionResult Edit(int id)
        {
            Dinner dinner = dinnerRepository.GetDinner(id);

            //ViewData["Countries"] = new SelectList(PhoneValidator.Countries, dinner.Country);

            if (!dinner.IsHostedBy(User.Identity.Name))
                return View("InvalidOwner");

            return View(new DinnerFormViewModel(dinner));
        }

        //
        // POST: /Dinners/Edit/[ID]
        [AcceptVerbs(HttpVerbs.Post), Authorize]
        public ActionResult Edit(int id, FormCollection formValues)
        {

            Dinner dinner = dinnerRepository.GetDinner(id);

            if (!dinner.IsHostedBy(User.Identity.Name))
                return View("InvalidOwner");

            try
            {
                UpdateModel(dinner);
                dinnerRepository.Save();

                return RedirectToAction("Details", new { id = dinner.DinnerID });

            }
            catch
            {
                foreach (var issue in dinner.GetRuleViolations())
                {
                    ModelState.AddModelError(issue.PropertyName, issue.ErrorMessage);

                    //ViewData["Countries"] = new SelectList(PhoneValidator.Countries, dinner.Country);
                }


                return View(new DinnerFormViewModel(dinner));
            }     

        }

        //
        // GET: /Dinners/Create/
        [Authorize]
        public ActionResult Create() {

        Dinner dinner = new Dinner()
        {
            EventDate = DateTime.Now.AddDays(7)
        };

            return View(new DinnerFormViewModel(dinner));

        }

        //
        // POST: /Dinners/Create/
        [AcceptVerbs(HttpVerbs.Post), Authorize]
        public ActionResult Create(Dinner dinner)
        {

            if (ModelState.IsValid)
            {

                try
                {
                    dinner.HostedBy = User.Identity.Name;

                    RSVP rsvp = new RSVP();
                    rsvp.AttendeeName = User.Identity.Name;
                    dinner.RSVPs.Add(rsvp);

                    dinnerRepository.Add(dinner);
                    dinnerRepository.Save();

                    return RedirectToAction("Details", new { id = dinner.DinnerID });
                }
                catch
                {
                    foreach (var issue in dinner.GetRuleViolations())
                    {
                        ModelState.AddModelError(issue.PropertyName, issue.ErrorMessage);
                    }

                    return View(new DinnerFormViewModel(dinner));
                }
            }

            return View(new DinnerFormViewModel(dinner));
        }


        //
        // GET: /Dinners/Delete/[ID]
        public ActionResult Delete(int id)
        {

            Dinner dinner = dinnerRepository.GetDinner(id);

            if (dinner == null)
                return View("NotFound");
            else
                return View(dinner);
        }

        //
        // POST: /Dinners/Delete/[ID]

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Delete(int id, string confirmButton)
        {

            Dinner dinner = dinnerRepository.GetDinner(id);

            if (dinner == null)
                return View("NotFound");

            dinnerRepository.Delete(dinner);
            dinnerRepository.Save();

            return View("Deleted");
        }
    }
}

NerdDinner/NerdDinner/Controllers/RSVPController.cs
using NerdDinner.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NerdDinner.Controllers
{
    public class RSVPController : Controller
    {

        DinnerRepository dinnerRepository = new DinnerRepository();

        //
        // AJAX: /Dinners/RSVPForEvent/1

        [Authorize, AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Register(int id)
        {

            Dinner dinner = dinnerRepository.GetDinner(id);

            if (!dinner.IsUserRegistered(User.Identity.Name))
            {

                RSVP rsvp = new RSVP();
                rsvp.AttendeeName = User.Identity.Name;

                dinner.RSVPs.Add(rsvp);
                dinnerRepository.Save();
            }

            return Content("Thanks - see you there!");
        }
    }
}

NerdDinner/NerdDinner/Views/Dinners/Create.cshtml
@model NerdDinner.Models.Dinner

@{
    ViewBag.Title = "Create";
}

@Html.Partial("DinnerForm")

NerdDinner/NerdDinner/Views/Dinners/Delete.cshtml
@model NerdDinner.Models.Dinner

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<section class="card">
    <header class="card-header">
        <h3>Are you sure you want to delete this?</h3>
    </header>
    <article class="card-body">
        <p>
            Please confirm you want to cancel the dinner titled:
            <i>@Model.Title</i>
        </p>
    </article>
    <footer class="card-footer">
        <input type="submit" value="Delete" class="btn btn-default float-right" /> |
        @Html.ActionLink("Back to List", "Index")
    </footer>
</section>

}

NerdDinner/NerdDinner/Views/Dinners/Deleted.cshtml
<section class="card">
    <header class="card-header">
        <h2>Dinner Deleted</h2>
    </header>
    <article class="card-body">
        <p>Your dinner was successfully deleted.</p>
    </article>
    <footer class="card-footer">
        <a href="/dinners">Click for Upcoming Dinners</a>
    </footer>
</section>

NerdDinner/NerdDinner/Views/Dinners/Details.cshtml
@model NerdDinner.Models.Dinner

@{
    ViewBag.Title = "Details";
}

<section class="card">

    <div class="card-header">
        <h2>@Html.DisplayFor(model => model.Title)</h2>
    </div>
    <div class="card-body">

        @if (Request.IsAuthenticated)
        {
            if ( Model.IsUserRegistered(Context.User.Identity.Name) )
            {
                @: You are registered for this event! <br/>
            }
            else
            {
                @Ajax.ActionLink("RSVP for this event", "Register", "RSVP", new { id = Model.DinnerID }, new AjaxOptions { UpdateTargetId = "rsvpmsg" })
            }
        }
        else
        {
            @:<a href="/Account/Login">Login</a> To RSVP for this event. <br />
        }

        <p>
            <strong>When:</strong>
            @Html.DisplayFor(model => model.EventDate)
            <strong>At</strong>
            @Html.DisplayFor(model => model.EventDate)
        </p>
        <p>
            <strong>Where:</strong>
            @Html.DisplayFor(model => model.Address)
            @Html.DisplayFor(model => model.Country)
        </p>
        <p>
            <strong>Description:</strong>
            @Html.DisplayFor(model => model.Description)
        </p>
        <p>
            <strong>Organizer:</strong>
            @Html.DisplayFor(model => model.HostedBy)
            @Html.DisplayFor(model => model.ContactPhone)
        </p>
    </div>
    <div class="card-footer">
        @Html.ActionLink("Edit", "Edit", new { id = Model.DinnerID }) |
        @Html.ActionLink("Back to List", "Index")
    </div>

</section>

@*Cant do this as it is deprecated and doesnt exist anymore
https://stackoverflow.com/questions/8782697/are-microsoftajax-js-microsoftmvcajax-js-and-microsoftmvcvalidation-js-obsolete

<script src="/Scripts/MicrosoftAjax.js" type="text/javascript"></script>
<script src="/Scripts/MicrosoftMvcAjax.js" type="text/javascript"></script>*@

NerdDinner/NerdDinner/Views/Dinners/DinnerForm.cshtml
@model NerdDinner.Models.DinnerFormViewModel


<section class="card">
    <header class="card-header">
        @Html.DisplayFor(model => model.Dinner.Title)
    </header>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        <article class="card-body">
            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Dinner.DinnerID)

                <div class="form-group">
                    @Html.LabelFor(model => model.Dinner.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Dinner.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Dinner.Title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Dinner.EventDate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Dinner.EventDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Dinner.EventDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Dinner.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Dinner.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Dinner.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Dinner.ContactPhone, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Dinner.ContactPhone, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Dinner.ContactPhone, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Dinner.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Dinner.Address, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Dinner.Address, "", new { @class = "text-danger" })
                    </div>
                </div>
                 
                <div class="form-group"> 
                    @Html.LabelFor(model => model.Dinner.Country, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @*@Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })*@
                        @Html.DropDownList("Country", Model.Countries) 
                        @Html.ValidationMessageFor(model => model.Dinner.Country, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Dinner.Latitude, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Dinner.Latitude, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Dinner.Latitude, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Dinner.Longitude, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Dinner.Longitude, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Dinner.Longitude, "", new { @class = "text-danger" })
                    </div>
                </div>

            </div>

        </article>
        <footer class="card-footer">
            <input type="submit" value="Save" class="btn btn-default float-right" />
            @Html.ActionLink("Back to List", "Index")
        </footer>
    }
</section>

NerdDinner/NerdDinner/Views/Dinners/Edit.cshtml
@model NerdDinner.Models.Dinner

@{
    ViewBag.Title = "Edit";
}


@Html.Partial("DinnerForm")

NerdDinner/NerdDinner/Views/Dinners/Index.cshtml
@model IEnumerable<NerdDinner.Models.Dinner>



@*   NerdDinner.Helpers.PaginatedList<Dinner>    *@

    @{
        ViewBag.Title = "Index";
    }


    <section class="card">

        <div class="card-header">
            <h2>Upcoming Events</h2>
        </div>
        <div class="card-body">
            <ul>
                @foreach (var dinner in Model)
            {
                    <li>@Html.ActionLink(dinner.Title, "Details", new { id = dinner.DinnerID }) on @Html.DisplayFor(modelItem => dinner.EventDate) at @Html.DisplayFor(modelItem => dinner.EventDate)</li>
                }
            </ul>

        </div>
        <div class="card-footer">
            @Html.ActionLink("Create New", "Create")



            @*   Paging Cant Get to Work    *@



        </div>

    </section>

NerdDinner/NerdDinner/Views/Dinners/InvalidOwner.cshtml
<h2>Error Accessing Dinner</h2>

<p>Sorry - but only the host of a Dinner can edit or delete it.</p>

NerdDinner/NerdDinner/Views/Dinners/NotFound.cshtml
@{
    ViewBag.Title = "Dinner Not Found";
}

<h2>NotFound</h2>
<p>Sorry - but the dinner you requested doesn't exist or was deleted.</p>